server.port=8082

spring.datasource.url=jdbc:h2:mem:storedb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

central.base-url=http://localhost:8081
central.http.connect-timeout-ms=300
central.http.read-timeout-ms=500

aws.region=us-east-1
aws.endpoint=http://localhost:4566
aws.queue-url=http://localhost:4566/000000000000/inv-loja-01

resilience4j.circuitbreaker.instances.centralApi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.centralApi.slidingWindowSize=50
resilience4j.circuitbreaker.instances.centralApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.centralApi.slowCallDurationThreshold=400ms
resilience4j.circuitbreaker.instances.centralApi.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.centralApi.minimumNumberOfCalls=20
resilience4j.circuitbreaker.instances.centralApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.centralApi.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.centralApi.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.instances.centralApi.maxAttempts=3
resilience4j.retry.instances.centralApi.waitDuration=100ms
resilience4j.retry.instances.centralApi.enableExponentialBackoff=true
resilience4j.retry.instances.centralApi.exponentialBackoffMultiplier=2

management.endpoints.web.exposure.include=health,info

# management.endpoints.web.exposure.include=health,info,prometheus
# management.endpoint.health.probes.enabled=true


logging.level.com.inventario.epiloja=INFO
logging.level.org.springframework.web.client.RestClient=INFO

